name: Build assets

on: [push]

jobs:
  build-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NPM dependencies
        run: npm ci

      - name: Compile assets
        run: npm run build

      - name: Create pull request with changes
        uses: peter-evans/create-pull-request@v4
